name: Manual workflow
on:
  workflow_dispatch:
     inputs:
      name: 
        description: 'Name'
        type: sring
        default: 'test' 

jobs: 
    manual: 
      runs-on: self-hosted
      steps:
         - name: Greetings
           run: apt install npm
